djangoProject/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from djangoProject.views import *

from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
   openapi.Info(
      title="Snippets API",
      default_version='v1',
      description="Test description",
      terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="contact@snippets.local"),
      license=openapi.License(name="BSD License"),
   ),
   public=True,
   permission_classes=[permissions.AllowAny],
)

urlpatterns = [
    path('admin/', admin.site.urls),

    # 홈
    path('', ArticleListPreview.as_view(), name='home'),
    path('intro/', Introduce.as_view(), name='introduce'),
    path('article/', include('article.urls')),

    # 공지사항
    path('notice/', include('notice.urls')),

    # 기술설정
    path('threshold/', include('threshold.urls')),
    path('sanction/', include('sanction.urls')),


    # 기술사용
    path('uploader/', include('uploader.urls')),

    # 마이페이지
    path('mysite/', include('mysite.urls')),

    # 로그인, 회원가입
    path('account/', include('account.urls')),

    # #url(r'^swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    # path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    # path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/urls.py
from django.urls import path, reverse
from . import views

app_name = 'mysite'

#url = reverse('page-detail', kwargs={'file_pk': 1, 'page_pk':1})

urlpatterns = [
    path('', views.FileListView.as_view(), name='file_list'),
    path('<str:pk>', views.FilePageListView.as_view(), name='page_list'),
    path('detail/<int:pk>', views.PageDetailView.as_view(), name='page_detail'),
]

mysite/models.py
from django.urls import reverse

from django.core.validators import FileExtensionValidator
from django.conf import settings
from django.db import models

from uploader.utils import rename_file_to_uuid
from threshold.models import SetThreshold
from uploader.models import UploadFile

class File(models.Model):
    # 파일 정보
    id = models.BigAutoField(help_text="File ID", primary_key=True)
    title = models.CharField(max_length=100, null=True)
    file = models.FileField(null=True, blank=True, upload_to=rename_file_to_uuid, validators=[FileExtensionValidator(allowed_extensions=['tif'])])
    filename = models.CharField(max_length=128, verbose_name='파일명')
    threshold = models.ForeignKey('threshold.SetThreshold', on_delete=models.SET_DEFAULT, default=80, verbose_name='임계치')
    commit_date = models.DateTimeField(auto_now_add=True, verbose_name='등록시간')
    description = models.TextField(verbose_name='설명')
    writer = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True, verbose_name='작성자')

    RESULT_CHOICES = [
        ('DANGER', '위험'),
        ('SAFE', '안전'),
    ]
    result = models.CharField(max_length=10, choices=RESULT_CHOICES, verbose_name='결과', blank=True, null=True)

    COMMIT_STATUS_CHOICES = [
        ('WAIT', '분석대기'),
        ('ONGO', '분석중'),
        ('DONE', '분석완료'),
    ]
    commit_status = models.CharField(max_length=4, choices=COMMIT_STATUS_CHOICES, default='WAIT', verbose_name='상태', blank=True, null=True)

    def __str__(self):
        return self.title

class Page(models.Model):
    id = models.BigAutoField(help_text="Page ID", primary_key=True)
    file = models.ForeignKey(File, blank=True, null=True, verbose_name='파일', related_name="uploaded_file", on_delete=models.CASCADE, db_column="file")
    title = models.CharField(max_length=100, null=True)
    description = models.TextField(null=True)

    filename = models.CharField(null=True, max_length=128)
    page_num = models.PositiveIntegerField(verbose_name='페이지')
    img_dir = models.TextField(blank=True, null=True, verbose_name='이미지')
    writer = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, verbose_name='작성자')

    box_json = models.TextField(blank=True, null=True)
    content = models.TextField(null=True, verbose_name='내용')
    is_safe = models.BooleanField(null=True, verbose_name='안전여부', default=False)

    def get_absolute_url(self):
        return reverse('mysite:page_detail', kwargs={'pk':self.pk})

mysite/views.py
from django.shortcuts import render, get_object_or_404

from django.views.generic import ListView, DetailView
from .models import *
from django.contrib import messages
from django.db.models import Q

from sanction.models import *
from threshold.models import SetThreshold

class FileListView(ListView):
    model = File
    paginate_by = 8
    template_name = 'mysite/file_list.html'  #DEFAULT : <app_label>/<model_name>_list.html
    context_object_name = 'file_list'        #DEFAULT : <model_name>_list

    def get_queryset(self):
        search_keyword = self.request.GET.get('q', '')
        file_list = File.objects.order_by('-id')

        if search_keyword:
            if len(search_keyword) > 1:
                search_file_list = file_list.filter(
                    Q(title__icontains=search_keyword)
                )
                return search_file_list
            else:
                messages.error(self.request, '검색어는 2글자 이상 입력해주세요.')
        return file_list

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        paginator = context['paginator']
        page_numbers_range = 5
        max_index = len(paginator.page_range)

        page = self.request.GET.get('page')
        current_page = int(page) if page else 1

        start_index = int((current_page - 1) / page_numbers_range) * page_numbers_range
        end_index = start_index + page_numbers_range
        if end_index >= max_index:
            end_index = max_index

        page_range = paginator.page_range[start_index:end_index]
        context['page_range'] = page_range

        search_keyword = self.request.GET.get('q', '')

        if len(search_keyword) > 1:
            context['q'] = search_keyword

        return context

class FilePageListView(ListView):
    model = Page
    template_name = 'mysite/page_list.html'  #DEFAULT : <app_label>/<model_name>_list.html
    context_object_name = 'page_list'        #DEFAULT : <model_name>_list
    sanction_list = SanctionMain.objects.all().values_list('sdn_name', flat=True)
    paginate_by = 10

    def get_queryset(self):
        self.file = get_object_or_404(File, filename=self.kwargs['pk'])
        return Page.objects.filter(file=self.file)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        paginator = context['paginator']
        page_numbers_range = 5
        max_index = len(paginator.page_range)

        page = self.request.GET.get('page')
        current_page = int(page) if page else 1

        start_index = int((current_page - 1) / page_numbers_range) * page_numbers_range
        end_index = start_index + page_numbers_range
        if end_index >= max_index:
            end_index = max_index

        page_range = paginator.page_range[start_index:end_index]
        context['page_range'] = page_range

        search_keyword = self.request.GET.get('q', '')

        if len(search_keyword) > 1:
            context['q'] = search_keyword

        return context

import jellyfish, re
import json
import cv2
import numpy as np
import matplotlib.pyplot as plt
from pytesseract import Output
import pytesseract
import re
from save_rect_dict import save_rect_dict

import logging

logger = logging.getLogger(__name__)

class PageDetailView(DetailView):
    model = Page
    template_name = 'mysite/page_detail.html'

    def get_queryset(self):
        return Page.objects.all()

    # 편집거리 이용해서 검출
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # 제재대상 데이터 가져옴
        sanction_list = SanctionMain.objects.all().values_list('sdn_name', flat=True)
        sdn_name = {}

        # full matching
        for sanction in sanction_list:
            #sanction = re.sub('[^a-zA-Z0-9]', '', sanction).strip()
            if sanction in self.object.content:
                context['result'] = '제재 대상 검출'
                sdn_name[sanction] = 100

        #docs = self.object.content.split(' ').remove('')
        #text = re.sub(r"[^a-zA-Z0-9 ]", "", self.object.content)
        docs = []
        for s in self.object.content.split():
            s= re.sub(r"[^a-zA-Z0-9 ]","", s)
            docs.append(s)

        # 임계치 데이터를 가져옴
        r = self.object.file.threshold.threshold
        for doc in docs:
            for sanction in sanction_list:
                sanction = re.sub(r"[^a-zA-Z0-9 ]","", sanction)
                if jellyfish.jaro_winkler(sanction, doc) * 100 > r:
                    # logger.error(sanction)
                    context['result'] = '제재 대상 검출'
                    sdn_name[sanction] = round(jellyfish.jaro_winkler(sanction, doc) * 100, 2)

        context['sanction'] = sdn_name.items()

        return context

mysite/templates/mysite/file_list.html
{% extends 'base.html' %}
{% block title %}file_list.html{% endblock %}

{% block content %}
    {% load static %}
    <!-- Page Content-->
    <section class="py-5 bg-light">
        <div class="container px-5">
            <div class="row gx-5">
                <h2 class="fw-bolder fs-5 mb-4">파일 리스트</h2>

                <form action="" method="GET">
                    <div class="ms-xl-4">
                        <div style="float: right;" class="input-group mb-2">
                            <div class="input-group mb-2">
                                <input class="form-control" name="q" value="{{ q }}" type="text" placeholder="검색어를 입력해주세요." aria-label="검색어를 입력해주세요."/>
                                <button class="btn btn-md btn-outline-dark" id="search_btn" type="submit">검색</button>
                            </div>
                        </div>
                    </div>
                </form>

                {% if q %}
                <h5>><i class="fas fa-search"></i>'{{ q }}' 검색 결과입니다.</h5>
                {% endif %}

                <table class="table">
                    <thead>
                        <tr class="text-center thead-dark">
                            <th>번호</th>
                            <th style="width:20%">파일명</th>
                            <th>시간</th>
                            <th>임계치</th>
                            <th style="width:30%">설명</th>
                            <th>작성자</th>
                            <th>상태</th>
                        </tr>
                        {% if q %}
                            {% if file_fixed %}
                                {% for file in file_fixed %}
                                    <tr class="text-center" style="cursor:pointer;" onclick="location.href='mysite/{{ file.filename }}'">
                                        <td>{{ file.id }}</td>
                                        <td>{{ file.title }}</td>
                                        <td>{{ file.commit_date|date:'Y. m. d' }}</td>
                                        <td>{{ file.threshold.threshold }}</td>
                                        <td>{{ file.description }}</td>
                                        <td>{{ file.writer }}</td>
                                        <td>{{ file.get_commit_status_display }}</td>
                                    </tr>
                                {% endfor %}
                            {% endif %}
                        {% endif %}

                    </thead>
                    <tbody>
                    {% if file_list %}
                        {% for file in file_list %}
                            <tr class="text-center" style="cursor:pointer;" onclick="location.href='{{ file.filename }}'">
                                <td>{{ file.id }}</td>
                                <td>{{ file.title }}</td>
                                <td>{{ file.commit_date|date:'Y. m. d' }}</td>
                                <td>{{ file.threshold.threshold }}</td>
                                <td>{{ file.description }}</td>
                                <td>{{ file.writer }}</td>
                                <td>{{ file.get_commit_status_display }}</td>
                            </tr>
                        {% endfor %}
                    {% else %}
                        <tr>
                            <td colspan="3">파일이 없습니다.</td>
                        </tr>
                    {% endif %}
                    </tbody>
                </table>
            </div>

            <div class="col-md-offset-6">
                {% if is_paginated %}
                <!-- <ul class="pagination justify-content-center pagination-sm"> -->
                <ul class="pagination justify-content-center">
                    {% if page_obj.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="?type={{ type }}&q={{ q }}&page={{ page_obj.previous_page_number }}"
                            tabindex="-1" style="font-size: 15px;">이전</a>
                    </li>
                    {% else %}
                    <li class="page-item disabled">
                        <a class="page-link" href="#" tabindex="-1" style="font-size: 15px;">이전</a>
                    </li>
                    {% endif %}

                    {% for page in page_range %}
                    <li class="page-item {% if page == page_obj.number %} activate {% endif %}">
                        <a class="page-link" href="?type={{ type }}&q={{ q }}&page={{ page }}" style="font-size: 15px;">{{ page }}</a>
                    </li>
                    {% endfor %}

                    {% if page_obj.has_next %}
                    <li class="page-item">
                        <a class="page-link"
                            href="?type={{ type }}&q={{ q }}&page={{ page_obj.next_page_number }}" style="font-size: 15px;">다음</a>
                    </li>
                    {% else %}
                    <li class="page-item disabled">
                        <a class="page-link" href="#" style="font-size: 15px;">다음</a>
                    </li>
                    {% endif %}
                </ul>
                {% endif %}
            </div>
        </div>
    </section>

{% endblock %}

mysite/templates/mysite/page_detail.html
{% extends 'base.html' %}
{% block title %}page_detail.html{% endblock %}
{% block head %}
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/1.3.3/jspdf.min.js"></script>
<script src="https://html2canvas.hertzen.com/dist/html2canvas.js"></script>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
    function getPDF(){

    var HTML_Width = $(".canvas_div_pdf").width();
    var HTML_Height = $(".canvas_div_pdf").height();
    var top_left_margin = 15;
    var PDF_Width = HTML_Width+top_left_margin;
    var PDF_Height = PDF_Width+top_left_margin;
    var canvas_image_width = HTML_Width;
    var canvas_image_height = HTML_Height;

    var totalPDFPages = Math.ceil(HTML_Height/PDF_Height)-1;

    html2canvas($(".canvas_div_pdf")[0],{allowTaint:true}).then(function(canvas) {
        canvas.getContext('2d');

        console.log(canvas.height+"  "+canvas.width);

        var imgData = canvas.toDataURL("image/jpeg", 1.0);
        var pdf = new jsPDF('p', 'pt',  [PDF_Width, PDF_Height]);
        pdf.addImage(imgData, 'JPG', top_left_margin, top_left_margin,canvas_image_width,canvas_image_height);

        for (var i = 1; i <= totalPDFPages; i++) {
            pdf.addPage(PDF_Width, PDF_Height);
            pdf.addImage(imgData, 'JPG', top_left_margin, -(PDF_Height*i)+(top_left_margin*4),canvas_image_width,canvas_image_height);
        }
        pdf.save("AML-Document.pdf");
        });
	};
</script>
{% endblock %}
{% block content %}
    {% load static %}
    <!-- Page Content-->
    <section class="py-5">
    <div class="container px-5 my-5">
        <!-- PDF 저장시 표시 되는 공간입니다 -->
        <div class="canvas_div_pdf">
            <div class="row gx-5">
                <div class="col-lg-6">
                    <article>
                        <header class="mb-4">
                            <h2 class="fw-bolder fs-5 mb-4">{{ page.title }}의 {{ page.page_num }} 페이지 상세 화면</h2>
                        </header>

                        <!-- 캔버스에 SANCTION LIST 박스처리 -->
                        <figure class="mb-4">
                        <canvas id="canvas" width="480" height="640" style="border:1px solid #d3d3d3;">
                            Your browser does not support the HTML5 canvas tag.
                        </canvas>
                        <script type="text/javascript">
                            var jsonArrStr = '{{ page.box_json |safe|escape}}';
                            var jsonArr = JSON.parse(jsonArrStr);

                            var ocrInfo = {
                                imgUrl : '{% get_static_prefix %}upload/{{page.filename}}_{{page.page_num}}.jpg',
                                ocrLoc : jsonArr
                            }
                            /**
                            * Canvas 설정
                            */
                            var setCanvas = function(ocrInfo){
                            var canvas = document.getElementById('canvas');
                                if (canvas.getContext) {

                                    var ctx = canvas.getContext('2d');
                                    var imageObj = new Image();
                                    imageObj.onload = function () {
                                        // 원본 너비와 높이를 구해서 박스값 변환하는데 사용합니다.
                                        var originWidth = this.width;
                                        var originHeight = this.height;

                                        canvas.width=480;
                                        canvas.height=640;
                                        ctx.drawImage(imageObj, 0, 0, 480, 640);
                                        // multi boxing 처리 (480 * 640 사이즈에 맞도록 변환)
                                        $.each(ocrInfo.ocrLoc, function(key, item){
                                            ctx.strokeStyle = item.color;
                                            ctx.lineWidth = 2;
                                            ctx.strokeRect(item.x*(480/originWidth), item.y*(640/originHeight), item.w*(480/originWidth), item.h*(640/originHeight));

                                            // Text 처리
                                            ctx.textBaseline = 'top';
                                            ctx.font="11px Verdana";
                                            ctx.fillStyle = "red";
                                            ctx.fillText(item.text, item.x*(480/originWidth), item.y*(640/originHeight) + item.h*(640/originHeight) + 5);
                                            ctx.fill();
                                        });
                                    };
                                    imageObj.src = ocrInfo.imgUrl;
                                    }
                            };
                            // set Canvas
                            setCanvas(ocrInfo);
                        </script>
                        </figure>
                    </article>

                </div>

                <div class="col-lg-5">
                    <div onclick="getPDF()" class="d-flex align-items-center mt-lg-4 mb-4">
                        <a href="#" class="btn btn-warning btn-icon-split">
                            <span class="icon text-white-50">
                                <i class="fas fa-exclamation-triangle"></i>
                            </span>
                            <span class="text">다운로드</span>
                        </a>
                    </div>
                    <div class="card mb-4">
                        <div class="card-header">
                            최종결론
                        </div>
                        <div class="card-body">
                            {% if result %}
                                {{ result }}
                            {% else %}
                                안전 서류
                            {% endif %}
                        </div>
                    </div>
                    <div class="card mb-4">
                        <div class="card-header">
                            판단근거
                        </div>
                        <div class="card-body">
                            {% if sanction %}
                                {% for sanction_name in sanction %}
                                    제재 대상 : {{ sanction_name.0 }}, 점수 : {{ sanction_name.1 }} <br/>
                                {% endfor %}
                            {% else %}
                                제재 대상이 발견되지 않았습니다
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </section>
{% endblock %}

mysite/templates/mysite/page_list.html
{% extends 'base.html' %}
{% block title %}page_list.html{% endblock %}
{% block content %}
{% load static %}

<style type="text/css">
#pageloader {
  background: rgba( 255, 255, 255, 0.8 );
  display: none;
  height: 100%;
  position: fixed;
  width: 100%;
  z-index: 9999;
}

#pageloader img {
  left: 50%;
  margin-left: -32px;
  margin-top: -32px;
  position: absolute;
  top: 50%;
}
</style>

{#<script>#}
{#$(document).ready(function(){#}
{#  $('.table td').onclick = function(){#}
{#      ("#pageloader").fadeIn();#}
{#  });//submit#}
{#});//document ready#}
{#</script>#}
{##}
{#<div id="pageloader">#}
{#    <img src="http://cdnjs.cloudflare.com/ajax/libs/semantic-ui/0.16.1/images/loader-large.gif" alt="processing..." />#}
{#</div>#}

<!-- Page Content-->
<section class="py-5 bg-light">
    <div class="container px-5">
        <div class="row gx-5">
            <table class="table">
                <thead>
                    <tr class="text-center thead-dark">
                        <th>번호</th>
                        <th>제목</th>
                        <th>결과</th>
                        <th>작성자</th>
                    </tr>
                </thead>
                <tbody>
                {% if page_list %}
                    {% for page in page_list %}
                        <tr class="text-center" style="cursor:pointer;" onclick="location.href='{{ page.get_absolute_url }}'">
                            <td>{{ page.page_num }}</a></td>
                            <td>{{ page.title }}</td>
                            <td>{{ result }}</td>
                            <td>{{ page.writer }}</td>
                        </tr>
                    {% endfor %}
                {% else %}
                    <tr>
                        <td colspan="3">파일이 없습니다.</td>
                    </tr>
                {% endif %}
                </tbody>
            </table>
        </div>

        <div class="col-md-offset-6">
            {% if is_paginated %}
            <!-- <ul class="pagination justify-content-center pagination-sm"> -->
            <ul class="pagination justify-content-center">
                {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?type={{ type }}&q={{ q }}&page={{ page_obj.previous_page_number }}"
                        tabindex="-1" style="font-size: 15px;">이전</a>
                </li>
                {% else %}
                <li class="page-item disabled">
                    <a class="page-link" href="#" tabindex="-1" style="font-size: 15px;">이전</a>
                </li>
                {% endif %}

                {% for page in page_range %}
                <li class="page-item {% if page == page_obj.number %} activate {% endif %}">
                    <a class="page-link" href="?type={{ type }}&q={{ q }}&page={{ page }}" style="font-size: 15px;">{{ page }}</a>
                </li>
                {% endfor %}

                {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link"
                        href="?type={{ type }}&q={{ q }}&page={{ page_obj.next_page_number }}" style="font-size: 15px;">다음</a>
                </li>
                {% else %}
                <li class="page-item disabled">
                    <a class="page-link" href="#" style="font-size: 15px;">다음</a>
                </li>
                {% endif %}
            </ul>
            {% endif %}
        </div>
    </div>
</section>

{% endblock %}