account/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'account'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='account/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
]

article/urls.py
from django.urls import path
from . import views

app_name = 'article'

urlpatterns = [
    path('', views.ArticleList.as_view(), name='index'),
]

djangoProject/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from djangoProject.views import *

from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
   openapi.Info(
      title="Snippets API",
      default_version='v1',
      description="Test description",
      terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="contact@snippets.local"),
      license=openapi.License(name="BSD License"),
   ),
   public=True,
   permission_classes=[permissions.AllowAny],
)

urlpatterns = [
    path('admin/', admin.site.urls),

    # 홈
    path('', ArticleListPreview.as_view(), name='home'),
    path('intro/', Introduce.as_view(), name='introduce'),
    path('article/', include('article.urls')),

    # 공지사항
    path('notice/', include('notice.urls')),

    # 기술설정
    path('threshold/', include('threshold.urls')),
    path('sanction/', include('sanction.urls')),


    # 기술사용
    path('uploader/', include('uploader.urls')),

    # 마이페이지
    path('mysite/', include('mysite.urls')),

    # 로그인, 회원가입
    path('account/', include('account.urls')),

    # #url(r'^swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    # path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    # path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/urls.py
from django.urls import path, reverse
from . import views

app_name = 'mysite'

#url = reverse('page-detail', kwargs={'file_pk': 1, 'page_pk':1})

urlpatterns = [
    path('', views.FileListView.as_view(), name='file_list'),
    path('<str:pk>', views.FilePageListView.as_view(), name='page_list'),
    path('detail/<int:pk>', views.PageDetailView.as_view(), name='page_detail'),
]

notice/urls.py
from django.urls import path, re_path
from . import views

app_name = 'notice'

urlpatterns = [
    path('', views.NoticeList.as_view(), name='index'),
    path('<int:pk>/', views.NoticeDetail.as_view(), name='detail'),
]

sanction/urls.py
from django.urls import path, re_path
from . import views

app_name = 'sanction'

urlpatterns = [
    path('', views.SanctionListView.as_view(), name='index'),
    path('<int:pk>/', views.SanctionDetailView.as_view(), name='detail'),
]

templates/base.html
<!doctype html>
{% load static %}
<html lang="ko">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />

        <title>base.html</title>
        {% block head %}
        {% endblock %}

    </head>
    <!-- jQuery -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <!-- Core theme JS-->
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script type="module" src="{% static 'js/spin.js' %}"></script>

    {% block script %}
    {% endblock %}

    <body>
    {% include "navbar.html" %}

    <!-- 기본 템플릿 안에 삽입될 내용 start -->
    {% block content %}
    {% endblock %}
    <!-- 기본 템플릿 안에 삽입될 내용 END -->

    <!-- Footer-->
    <footer class="py-5 bg-dark">
        <div class="container px-5"><p class="m-0 text-center text-white">Copyright &copy; Anti-TBML 2021</p></div>
    </footer>

    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous"></script>

    </body>
</html>

templates/form_errors.html
<!-- form.errors.html 템플릿은 로그인 실패시 로그인이 왜 실패했는지알려주는 역할을 한다 -->

{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %} <!-- 필드 오류를 출력한다 -->
            <div class="alert alert-danger">
                <strong>{{ field.lael }}</strong>
                {{ error }}
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}   <!-- 넌필드 오류를 출력한다. -->
        <div class="alert alert-danger">
            <strong>{{ error }}</strong>
        </div>
    {% endfor %}
{% endif %}

templates/home.html
{% extends 'base.html' %}
{% block title %}home.html{% endblock %}

{% block content %}
{% load static %}
<!-- Header-->
<header class="bg-dark py-5">
    <div class="container px-5">
        <div class="row gx-5 align-items-center justify-content-center">
            <div class="col-xl-5 col-xxl-6 d-none d-xl-block text-center">
                <img class="img-fluid rounded-3 my-5" src={% static "img/home.png" %} height="250" width="250" alt="..." /></div>
            <div class="col-lg-8 col-xl-7 col-xxl-6">
                <div class="my-5 text-center text-xl-start">
                    <h1 class="display-5 fw-bolder text-white mb-2">anti-TBML</h1>
                    <p class="lead fw-normal text-white-50 mb-4">무역서류를 기반으로 이상거래를 탐지하는 시스템 </p>
                    <div class="d-grid gap-3 d-sm-flex justify-content-sm-center justify-content-xl-start">
                        <a class="btn btn-primary btn-lg px-4 me-sm-3" href="{% url 'introduce' %}">Learn More</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</header>



<section class="py-5 bg-light">
    <div class="container px-5">
        <div class="row gx-5">
            <h2 class="fw-bolder fs-5 mb-4">관련 기사</h2>

            <!-- News item-->
            {% for article in articles %}
                <div class="mb-xl-5">
                    <div class="small text-muted">{{ article.release_date|date:'N d일, Y년' }}</div>
                    <a class="link-dark" href="{{ article.link }}"><h3>{{ article.title }}</h3></a>
                    <h6>{{ article.content }}</h6>
                </div>
           {% endfor %}

            <div class="text-end mb-5 mb-xl-0">
                <a class="text-decoration-none" href="#!">
                    More news
                    <i class="bi bi-arrow-right"></i>
                </a>
            </div>
        </div>
    </div>
</section>

{% endblock %}

templates/introduce.html
{% extends 'base.html' %}
{% block title %}introduce.html{% endblock %}

{% block content %}
    {% load static %}
    <!-- Page Content-->

    <section class="py-5">
        <div class="container px-5 my-5">
            <div class="text-center mb-5">
                <h1 class="fw-bolder">Our Work</h1>
                <p class="lead fw-normal text-muted mb-0">1조 portfolio</p>
            </div>
            <div class="row gx-5">
                <div class="col-lg-6">
                    <div class="position-relative mb-5">
                        <img class="img-fluid rounded-3 mb-3" src={% static "img/1.jpg" %} alt="..." />
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="position-relative mb-5">
                        <img class="img-fluid rounded-3 mb-3" src={% static "img/2.jpg" %} alt="..." />
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="position-relative mb-5 mb-lg-0">
                        <img class="img-fluid rounded-3 mb-3" src={% static "img/3.jpg" %} alt="..." />
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="position-relative">
                        <img class="img-fluid rounded-3 mb-3" src={% static "img/0.jpg" %} alt="..." />
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

templates/navbar.html
<!-- Responsive navbar-->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container px-5">
        <a class="navbar-brand" href="#!">Anti-TBML</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span></button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'home' %}">홈</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'notice:index' %}">공지사항</a></li>

                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="navbarDropdownBlog" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">기술설정</a>
                    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdownBlog">
                        <li><a class="dropdown-item" href="{% url 'threshold:threshold' %}">임계치 설정</a></li>
                        <li><a class="dropdown-item" href="{% url 'sanction:index' %}">제재 목록 검색</a></li>
                        <li><a class="dropdown-item" href="{% url 'article:index' %}">개발스토리</a></li>
                        <li><a class="dropdown-item" href="{% url 'introduce' %}">소개</a></li>
                    </ul>
                </li>

                <li class="nav-item"><a class="nav-link" href="{% url 'uploader:uploader' %}">기술사용</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'mysite:file_list' %}">마이페이지</a></li>
                <li class="nav-item">
                    {% if user.is_authenticated %}
                    <a class="nav-link" href="{% url 'account:logout' %}">{{ user.username }} (로그아웃)</a>
                    {% else %}
                    <a class="nav-link" href="{% url 'account:login' %}">로그인</a>
                    {% endif %}
                </li>
            </ul>
        </div>
    </div>
</nav>